### ISSUE TITLE
python binding

### ISSUE THREAD

**Issue by zetbouaka** [EeeUnS/onsen-downloader#2]
https://github.com/kkroening/ffmpeg-python

ffmpeg를 os.system으로 호출하는 것보다 python binding을 사용해 python 내부에서 처리할 수 있지 않을까요?

**Comment by EeeUnS** [comment]
이거 하려고 코드짰다가 포기했었습니다. readme에 나온내용으로만  일단 해봤는데 m3u8파일을 웹에서 받아와야하는과정에서 이거는 존재하는 파일을 연결하는 식인지 파일이 없다고 input에서부터 에러가 났었거든요.
혹시 방법있으면 직접 풀 리퀘스트 부탁드립니다.
